// Hugo Capitelli — Psychometric Profile
// Source: hugo-capitelli-psychometric-profile.yaml
// Generated by wf-forge-zero

export const profile = {
  meta: {
    subject: "Hugo Capitelli",
    date: "2026-02-19",
    coreIdentity: "O Visionário Perfeccionista",
    headline: "ENTP-A · Assessor DI/IC · Eneagrama Tipo 1 · E:93 C:91",
  },

  disc: {
    style: "Assessor",
    styleCode: "DI/IC",
    primaryTraits: [
      "Balanceia pessoas E controle de qualidade",
      "Vê tanto o big picture quanto os detalhes",
      "Assertivo sem ser agressivo",
      "Excele em explicar estratégia e passos para metas",
    ],
    underStress: "Pode se tornar crítico e impaciente com os outros",
    keepInMind: "Pode fazer suposições e ultrapassar limites de empoderamento",
    communicationDo: [
      "Pedir input sobre pessoas e tarefas específicas",
      "Concluir comunicação com ações e instruções específicas",
      "Cumprir o que diz — follow through",
      "Falar sobre sonhos e objetivos",
      "Ser crível e realista com informações",
      "Ser envolvente, estimulante e com ritmo rápido",
    ],
    communicationDont: [
      "Deixar decisões no ar",
      "Apressar questões sem ter buy-in",
      "Ser impessoal ou julgador",
      "Usar opinião de terceiros como evidência",
      "Ser irrealista com prazos",
      "Ser dogmático",
    ],
  },

  motivators: [
    { name: "Econômico", level: "HIGH" as const, score: 90, description: "Resultados bottom-line, mentalidade competitiva" },
    { name: "Individualista", level: "HIGH" as const, score: 85, description: "Autonomia, independência, destaque individual" },
    { name: "Poder", level: "HIGH" as const, score: 88, description: "Liderança, influência, controle do ambiente" },
    { name: "Teórico", level: "HIGH" as const, score: 82, description: "Necessidade de descobrir verdade, aprender" },
    { name: "Regulatório", level: "NEUTRAL" as const, score: 52, description: "Entende estrutura mas não se prende a regras" },
    { name: "Estético", level: "LOW" as const, score: 25, description: "Prático, pé no chão, utilitarista" },
    { name: "Altruísta", level: "LOW" as const, score: 20, description: "Difícil de manipular, determinado no caos" },
  ],

  mbti: {
    type: "ENTP-A",
    label: "O Debatedor (Assertive)",
    dimensions: [
      { name: "Energia", preference: "Extrovertido", score: 67, opposite: "Introvertido" },
      { name: "Informação", preference: "Intuitivo", score: 64, opposite: "Sensitivo" },
      { name: "Decisão", preference: "Pensamento", score: 53, opposite: "Sentimento", note: "Muito próximo do centro — usa ambos" },
      { name: "Estilo de Vida", preference: "Prospectando", score: 51, opposite: "Julgando", note: "O mais próximo do centro — altamente adaptável" },
      { name: "Identidade", preference: "Assertivo", score: 61, opposite: "Turbulento" },
    ],
    strengths: [
      { name: "Gerador de Ideias", detail: "Propõe conceitos frescos constantemente" },
      { name: "Improvisador Natural", detail: "Adapta-se quando as coisas não saem como planejado" },
      { name: "Comunicador Persuasivo", detail: "Articula pontos de vista de forma convincente" },
      { name: "Aprendiz Rápido", detail: "Absorve tópicos novos sem esforço" },
      { name: "Influência Energizante", detail: "Entusiasmo e humor mantêm motivação alta" },
      { name: "Pensador Independente", detail: "Questiona tradições e descobre oportunidades" },
    ],
    weaknesses: [
      { name: "Dificuldade com Organização", detail: "Rotinas e detalhes são desafiadores" },
      { name: "Impaciência com Tarefas Rotineiras", detail: "Tarefas repetitivas são negligenciadas" },
      { name: "Facilmente Distraído", detail: "Novas ideias capturam atenção, atrasam compromissos" },
      { name: "Crítico com Autoridade", detail: "Questionar regras pode comprometer relações" },
      { name: "Dificuldade de Compromisso", detail: "Novidade dificulta compromisso longo prazo" },
    ],
  },

  bigFive: {
    overall: {
      neuroticism: 47,
      extraversion: 93,
      openness: 80,
      agreeableness: 84,
      conscientiousness: 91,
    },
    details: [
      {
        factor: "Neuroticismo",
        code: "N",
        score: 47,
        level: "Baixo-Neutro",
        color: "#8B9CC4",
        interpretation: "Calmo, equilibrado, estável. Não reage com emoções intensas.",
        subfactors: [
          { name: "Ansiedade", score: 8 },
          { name: "Raiva", score: 9 },
          { name: "Melancolia", score: 6 },
          { name: "Autoconsciência", score: 9 },
          { name: "Impulsividade", score: 8 },
          { name: "Vulnerabilidade", score: 7 },
        ],
      },
      {
        factor: "Extroversão",
        code: "E",
        score: 93,
        level: "Muito Alto",
        color: "#C4A882",
        interpretation: "Sociável, extrovertido, enérgico, animado. Prefere estar perto de pessoas.",
        paradox: "Simpatia 19 (faz amigos fácil) + Sociabilidade 11 (evita multidões) = Social seletivo",
        subfactors: [
          { name: "Simpatia", score: 19 },
          { name: "Sociabilidade", score: 11 },
          { name: "Assertividade", score: 17 },
          { name: "Atividade", score: 17 },
          { name: "Busca de Sensações", score: 11 },
          { name: "Emoções Positivas", score: 18 },
        ],
      },
      {
        factor: "Abertura",
        code: "O",
        score: 80,
        level: "Alto",
        color: "#7C9E8F",
        interpretation: "Curioso, criativo, intelectual. Gosta de novidades e mudanças.",
        paradox: "Intelecto 18 (mente aberta) + Liberalismo 5 (conservador em valores) = Intelectual Conservador",
        subfactors: [
          { name: "Fantasia", score: 17 },
          { name: "Estética", score: 14 },
          { name: "Emotividade", score: 14 },
          { name: "Aventura", score: 12 },
          { name: "Intelecto", score: 18 },
          { name: "Liberalismo", score: 5 },
        ],
      },
      {
        factor: "Amabilidade",
        code: "A",
        score: 84,
        level: "Alto",
        color: "#C48BB4",
        interpretation: "Agradável, simpático, solidário. Forte interesse em atender necessidades dos outros.",
        paradox: "Altruísmo 19 + Modéstia 6 + Empatia 12 = Altruísta Dominante",
        subfactors: [
          { name: "Confiança", score: 18 },
          { name: "Moralidade", score: 12 },
          { name: "Altruísmo", score: 19 },
          { name: "Cooperação", score: 17 },
          { name: "Modéstia", score: 6 },
          { name: "Empatia", score: 12 },
        ],
      },
      {
        factor: "Conscienciosidade",
        code: "C",
        score: 91,
        level: "Muito Alto",
        color: "#7C9E8F",
        interpretation: "Define objetivos claramente e os realiza com determinação. Confiável e trabalhador.",
        paradox: "Realização 19 (workaholic) + Ordem 12 (não organizado) = Produtor Desorganizado",
        subfactors: [
          { name: "Autoeficácia", score: 18 },
          { name: "Ordem", score: 12 },
          { name: "Senso de Dever", score: 17 },
          { name: "Realização/Esforço", score: 19 },
          { name: "Autodisciplina", score: 13 },
          { name: "Cautela", score: 12 },
        ],
      },
    ],
  },

  enneagram: {
    primaryType: 1,
    typeName: "O Perfeccionista",
    matchPercent: 98,
    fullType: "1w2",
    wing: 2,
    wingScore: 78,
    tritype: "1-3-7",
    tritypeLabel: "The Visionary Achiever",
    tritypeInterpretation: "Perfeccionista + Realizador + Entusiasta. Motor: fazer a coisa CERTA de forma EXCELENTE enquanto APROVEITA o processo.",
    arrowGrowth: 7,
    arrowStress: 4,
    coreFear: "Ser falho, imperfeito, fazer algo inapropriado",
    coreDesire: "Viver de acordo com integridade pessoal. Ser correto, equilibrado, virtuoso",
    typeScores: [
      { type: 1, label: "Perfeccionista", score: 98, category: "body" as const },
      { type: 8, label: "Desafiador", score: 95, category: "body" as const },
      { type: 3, label: "Realizador", score: 97, category: "heart" as const },
      { type: 2, label: "Ajudante", score: 78, category: "heart" as const },
      { type: 7, label: "Entusiasta", score: 84, category: "head" as const },
      { type: 5, label: "Investigador", score: 74, category: "head" as const },
      { type: 6, label: "Leal", score: 63, category: "head" as const },
      { type: 4, label: "Individualista", score: 60, category: "heart" as const },
      { type: 9, label: "Pacificador", score: 49, category: "body" as const },
    ],
    thriving: ["Justo", "De coração aberto", "Ético", "Confiável", "Autoconsciente", "Respeitoso", "Inspirador"],
    underStress: ["Dogmático", "Impaciente", "Repreendendo", "Nervoso", "Controlando", "Obsessivo", "Autopunição"],
  },

  paradoxes: [
    {
      name: "Perfeccionista Flexível",
      frameworks: "Eneagrama 1 + MBTI P:51",
      description: "Busca excelência mas não se prende a estrutura rígida",
      insight: "A perfeição não precisa de método fixo — pode se manifestar de formas diferentes",
    },
    {
      name: "Social Seletivo",
      frameworks: "Big Five Simpatia:19 + Sociabilidade:11",
      description: "Faz amigos fácil mas evita multidões — qualidade > quantidade",
      insight: "Alta energia social canalizadaone-on-one, não em eventos ou crowds",
    },
    {
      name: "Altruísta Dominante",
      frameworks: "Big Five Altruísmo:19 + DISC Power HIGH + Modéstia:6",
      description: "Quer genuinamente ajudar mas de posição de liderança, não igualdade",
      insight: "A generosidade vem de um lugar de força — não é submissa, é estratégica",
    },
    {
      name: "Intelectual Conservador",
      frameworks: "Big Five Intelecto:18 + Liberalismo:5",
      description: "Mente aberta para ideias, conservador em valores",
      insight: "Questiona IDEIAS livremente mas preserva VALORES tradicionais",
    },
    {
      name: "Produtor Desorganizado",
      frameworks: "Big Five Realização:19 + Ordem:12",
      description: "Produz muito por drive interno, sem necessariamente ter sistemas",
      insight: "A produção vem de obsessão por resultado, não de método — funciona mas tem custo",
    },
    {
      name: "Harmonizador Assertivo",
      frameworks: "Big Five Cooperação:17 + Assertividade:17 + DISC D high",
      description: "Quer harmonia mas também quer liderar e direcionar",
      insight: "Tensão entre ceder e dirigir — resolve geralmente assumindo a direção",
    },
    {
      name: "Empático Meritocrático",
      frameworks: "Big Five Altruísmo:19 + Empatia:12",
      description: "Genuinamente generoso mas julgamentos baseados em mérito",
      insight: "Ajuda com propósito e direção, não com deferência",
    },
    {
      name: "Estável Perfeccionista",
      frameworks: "Neuroticismo:47 (baixo) + Eneagrama 1 (crítico interno forte)",
      description: "Baixo neuroticismo mas crítico interno exigente",
      insight: "Emocionalmente estável para o mundo mas internamente exigente consigo mesmo",
    },
  ],

  learningStyle: {
    kolbEstimate: "Convergente → Acomodador",
    description: "Prefere FAZER + PENSAR, com forte componente de EXPERIMENTAR. Aprende testando ideias na prática, debatendo, iterando rápido.",
    optimalEnvironment: [
      "Debate e argumentação (ENTP core)",
      "Projetos hands-on com feedback rápido",
      "Mentoria um-a-um (Sociabilidade baixa, Simpatia alta)",
      "Desafios intelectuais com aplicação prática",
      "Autonomia para explorar e depois consolidar",
    ],
    doesntLearnWell: [
      "Leitura passiva sem aplicação",
      "Teoria sem contexto prático",
      "Instrução estruturada e linear",
      "Ambientes sem possibilidade de questionar",
    ],
    decisionStyle: {
      primary: "Intuitivo-Racional",
      description: "Processa intuitivamente (N:64) mas decide com leve pendência racional (T:53). Usa AMBOS — leitura emocional + lógica. Sob pressão: assertividade direta (DISC D).",
    },
  },

  superpowers: [
    {
      name: "Persuasion Architect",
      evidence: "ENTP Comunicador Persuasivo + DISC criador de imagens mentais + Simpatia 19",
      leverage: "Pitch, fundraising, team building, parcerias",
    },
    {
      name: "Intellectual Firepower",
      evidence: "Intelecto 18 + Fantasia 17 + ENTP Gerador de Ideias + Teórico HIGH",
      leverage: "Estratégia, inovação, visão de produto, resolução de problemas",
    },
    {
      name: "Achievement Drive",
      evidence: "Realização-Esforço 19 + Econômico HIGH + Eneagrama 3:97% + Autoeficácia 18",
      leverage: "Goal-setting, pressão de execução, vantagem competitiva",
    },
    {
      name: "Emotional Stability Under Fire",
      evidence: "Neuroticismo 47 (baixo) + Assertivo 61% + Vulnerabilidade 7 (baixo)",
      leverage: "Gestão de crises, decisões de alto risco, liderança no caos",
    },
    {
      name: "Authentic Leadership",
      evidence: "Eneagrama 1 integridade + Senso de Dever 17 + Confiança 18",
      leverage: "Cultura, confiança, lealdade do time, autenticidade de marca",
    },
  ],
};

export type Profile = typeof profile;
export type MotivatorLevel = "HIGH" | "NEUTRAL" | "LOW";
